### ISSUE TITLE
What is embedded banking?

### ISSUE THREAD

**Issue by alexifti13** [jpmorgan-payments/embedded-banking#30]
[Embedded banking](https://www.treasuryprime.com/) is a specific type of embedded finance that entails a non-financial company offering banking products and services. Embedding banking typically involves bank accounts and linked debit cards. This can also be called Banking as a Service (BaaS).

**Comment by maria-mcparland** [comment]
Hi, you can find more information on our embedded banking solutions here: [https://www.jpmorgan.com/payments/solutions/embedded-banking](https://www.jpmorgan.com/payments/solutions/embedded-banking)

**Comment by kontel** [comment]
More information could be found at https://www.jpmorgan.com/payments/solutions/embedded-banking 

Also Embedded Finance is the integration of financial services and products, such as payment processing, banking and lending, into non-financial offerings. It enables non-financial businesses, such as retailers, bill payers and ride-sharing companies, to independently provide financial solutions tied to their products or services. It also allows non-financial businesses to enhance customer experience, boost retention, and offer financial services without the need to build extensive financial infrastructure or adhere to strict regulations like traditional financial institutions.
